version: '3'
services:
  iris:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: enerthon:latest
    container_name: enerthon
    ports:
      - 3000:3000
    restart: unless-stopped
